services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
        #    volumes:
        #      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
        #    volumes:
        #      - ./frontend:/app
